<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows10.0.19041.0</TargetFramework>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <AssemblyName>SnapCut</AssemblyName>
    <RootNamespace>Screenshot.App</RootNamespace>
    <ApplicationIcon>Assets\Screenshot.ico</ApplicationIcon>
    <Version>2.6.0</Version>
    <IncludeSourceRevisionInInformationalVersion>false</IncludeSourceRevisionInInformationalVersion>
    <Authors>九万字 (jiuwanzi-hui)</Authors>
    <Copyright>Copyright © 2026 九万字 (jiuwanzi-hui). All rights reserved.</Copyright>
    <Product>SnapCut</Product>
    <AssemblyTitle>SnapCut</AssemblyTitle>
    <Description>轻量 Windows 截图工具</Description>
  </PropertyGroup>

  <ItemGroup>
    <Resource Include="Assets\Screenshot.ico" />
    <Resource Include="Assets\DonateQr.jpg" />
    <Content Include="THIRD-PARTY-NOTICES.txt"
             CopyToOutputDirectory="PreserveNewest" />
    <Content Include="..\..\LICENSE"
             Link="LICENSE.txt"
             CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="BergamotTranslatorSharp" Version="0.5.1" />
    <PackageReference Include="Panlingo.LanguageIdentification.CLD3" Version="0.8.0" />
  </ItemGroup>

</Project>
